package com.hcentive.event.logging.domain;

import com.hcentive.utils.ext.HXConstants;

/**
 * This will define the NY-HX application name containing the specific event types for the specific sections.
 */

public enum EvtEventName {
	CONTACT_INFO_CHANGED("CONTACT_INFO_CHANGED"),
	CONTACT_INFO_DELETED("CONTACT_INFO_DELETED"),
	ID_PROOF_SUCCESS("ID_PROOF_SUCCESS"),
	ID_PROOF_FAIL("ID_PROOF_FAIL"),
	MANUALLY_ID_PROOFED("MANUALLY_ID_PROOFED"),
	APPLICATION_TYPE_DELETED("APPLICATION_TYPE_DELETED"),
	APPLICATION_TYPE_CHANGED("APPLICATION_TYPE_CHANGED"),
	ACCOUNT_CREATED("ACCOUNT_CREATED"),
	ACCOUNT_DEMOGRAPHICS_CREATED("ACCOUNT_DEMOGRAPHICS_CREATED"),
	ACCOUNT_DEMOGRAPHICS_CHANGED("ACCOUNT_DEMOGRAPHICS_CHANGED"),
	ACCOUNT_DEMOGRAPHICS_DELETED("ACCOUNT_DEMOGRAPHICS_DELETED"),
	HOME_ADDRESS_CREATED("HOME_ADDRESS_CREATED"),
	HOME_ADDRESS_CHANGED("HOME_ADDRESS_CREATED"),
	HOME_ADDRESS_DELETED("HOME_ADDRESS_DELETED"),
	MAILING_ADDRESS_CREATED("HOME_ADDRESS_DELETED"),
	MAILING_ADDRESS_CHANGED("MAILING_ADDRESS_CHANGED"),
	ADDITIONAL_ADDRESS_CHANGED("ADDITIONAL_ADDRESS_CHANGED"),
	ADDITIONAL_ADDRESS_CREATED("ADDITIONAL_ADDRESS_CREATED"),
	ADDITIONAL_ADDRESS_DELETED("ADDITIONAL_ADDRESS_DELETED"),
	HH_MEMBER_DEMOGRAPHICS_CREATED("HHM_APPLYING_INSURANCE_CREATED"),
	HH_MEMBER_DEMOGRAPHICS_CHANGED("HH_MEMBER_DEMOGRAPHICS_CHANGED"),
	HH_MEMBER_DEMOGRAPHICS_DELETED("HH_MEMBER_DEMOGRAPHICS_DELETED"),
	HHM_APPLYING_INSURANCE_CREATED("HHM_APPLYING_INSURANCE_CREATED"),
	HHM_APPLYING_INSURANCE_CHANGED("HHM_APPLYING_INSURANCE_CHANGED"),
	HHM_APPLYING_INSURANCE_DELETED("HHM_APPLYING_INSURANCE_DELETED"),
	HH_MEMBER_IDENTIFY_INFO_CREATED("HH_MEMBER_IDENTIFY_INFO_CREATED"),
	HH_MEMBER_IDENTIFY_INFO_CHANGED("HH_MEMBER_IDENTIFY_INFO_CHANGED"),
	HH_MEMBER_DOCUMENT_TYPE_CHANGED("HH_MEMBER_DOCUMENT_TYPE_CHANGED"),
	HH_MEMBER_IDENTIFY_INFO_DELETED("HH_MEMBER_IDENTIFY_INFO_DELETED"),
	HH_MEMBER_RELATIONSHIP_CREATED("HH_MEMBER_RELATIONSHIP_CREATED"),
	HH_MEMBER_RELATIONSHIP_CHANGED("HH_MEMBER_RELATIONSHIP_CHANGED"),
	HH_MEMBER_RELATIONSHIP_DELETED("HH_MEMBER_RELATIONSHIP_DELETED"),
	HH_MEMBER_ADDITIONAL_INFO_CHANGED("HH_MEMBER_ADDITIONAL_INFO_CHANGED"),
	HH_MEMBER_ADDED("HH_MEMBER_ADDED"),
	HH_MEMBER_REMOVED("HH_MEMBER_REMOVED"),
	WHERE_YOU_LIVE_CREATED("WHERE_YOU_LIVE_CREATED"),
	WHERE_YOU_LIVE_CHANGED("WHERE_YOU_LIVE_CHANGED"),
	WHERE_YOU_LIVE_DELETED("WHERE_YOU_LIVE_DELETED"),
	TAX_STATUS_CREATED("TAX_STATUS_CREATED"),
	TAX_STATUS_CHANGED("TAX_STATUS_CHANGED"),
	TAX_STATUS_DELETED("TAX_STATUS_DELETED"),
	INCOME_CREATED("INCOME_CREATED"),
	INCOME_CHANGED("INCOME_CHANGED"),
	INCOME_DELETED("INCOME_DELETED"),
	COVERAGE_INFO_CREATED("COVERAGE_INFO_CREATED"),
	COVERAGE_INFO_CHANGED("COVERAGE_INFO_CHANGED"),
	COVERAGE_INFO_DELETED("COVERAGE_INFO_DELETED"),
	APPLICATION_SIGNED("APPLICATION_SIGNED"),
	ENROLL_PLANS("ENROLL_PLANS"),
	LIFE_CHANGE_EVENT("LIFE_CHANGE_EVENT"),
	APPEAL_CREATED("APPEAL_CREATED"),
	ELIGIBILITY_RUN("ELIGIBILITY_RUN"),
	VERIFY_DOC("VERIFY_DOC"),
	UPLOAD_DOC("UPLOAD_DOC"),
	HH_MEMBER_NURSING_HOME_CARE_CHANGED("HH_MEMBER_NURSING_HOME_CARE_CHANGED"),
	ENROLLMENT_ADD("ENROLLMENT_ADD"),
	ENROLLMENT_DELETE("ENROLLMENT_DELETE"),
	ENROLLMENT_MODIFY("ENROLLMENT_MODIFY"),
	ELG_RESULT_PROG_CHANGE("ELG_RESULT_PROG_CHANGE"),
	ELG_RESULT_CHIP_TYPE_CHANGE("ELG_RESULT_CHIP_TYPE_CHANGE"),
	ELG_RESULT_MEDICAID_AID_CATEGORY_CHANGE("ELG_RESULT_MEDICAID_AID_CATEGORY_CHANGE"),
	ELG_RESULT_MEDICAID_COVERAGE_CODE_CHANGE("ELG_RESULT_MEDICAID_COVERAGE_CODE_CHANGE"),
	ELG_RESULT_MEDICAID_CHARGE_CODE_CHANGE("ELG_RESULT_MEDICAID_CHARGE_CODE_CHANGE"),
	HH_MEMBER_MARITAL_STATUS_CHANGED("HH_MEMBER_MARITAL_STATUS_CHANGED"),
	HH_MEMBER_DOB_CHANGED("HH_MEMBER_DOB_CHANGED"),
	HH_MEMBER_SSN_CHANGED("HH_MEMBER_SSN_CHANGED"),
	HH_MEMBER_NOSSN_REASON_CHANGED("HH_MEMBER_NOSSN_REASON_CHANGED"),
	HH_MEMBER_ITIN_CHANGED("HH_MEMBER_ITIN_CHANGED"),
	HH_MEMBER_HISPANIC_ORIGIN_CHANGED("HH_MEMBER_HISPANIC_ORIGIN_CHANGED"),
	HH_MEMBER_CITIZENSHIP_CHANGED("HH_MEMBER_CITIZENSHIP_CHANGED"),
	HH_MEMBER_RACE_CHANGED("HH_MEMBER_RACE_CHANGED"),
	HH_MEMBER_ETHNICITY_CHANGED("HH_MEMBER_ETHNICITY_CHANGED"),
	HH_MEMBER_FIRST_NAME_CHANGED("HH_MEMBER_FIRST_NAME_CHANGED"),
	HH_MEMBER_MIDDLE_NAME_CHANGED("HH_MEMBER_MIDDLE_NAME_CHANGED"),
	HH_MEMBER_LAST_NAME_CHANGED("HH_MEMBER_LAST_NAME_CHANGED"),
	HH_MEMBER_GENDER_CHANGED("HH_MEMBER_GENDER_CHANGED"),
	HH_MEMBER_SUFFIX_CHANGED("HH_MEMBER_SUFFIX_CHANGED"),
	HH_MEMBER_RESIDENCE_ADDRESS_CHANGED("HH_MEMBER_RESIDENCE_ADDRESS_CHANGED"),
	HH_MEMBER_RESIDENCE_ADDRESS_COUNTY_CHANGED("HH_MEMBER_RESIDENCE_ADDRESS_COUNTY_CHANGED"),
	HH_MEMBER_LEGAL_ADDRESS_CHANGED("HH_MEMBER_RESIDENCE_ADDRESS_CHANGED"),
	HH_MEMBER_LEGAL_ADDRESS_COUNTY_CHANGED("HH_MEMBER_RESIDENCE_ADDRESS_COUNTY_CHANGED"),
	HH_MEMBER_NOT_APPLYING_INELIGBLE("HH_MEMBER_NOT_APPLYING_INELIGBLE"),
	HH_MEMBER_AI_CHANGED("HH_MEMBER_AI_CHANGED"),
	HH_MEMBER_DISABILITY_CHANGED("HH_MEMBER_DISABILITY_CHANGED"),
	
	//Added as part of the implementation of Special Enrollment Period
	NEW_APP_MARRIAGE_OR_DOMESTIC_PARTNERSHIP("NEW_APP_MARRIAGE_OR_DOMESTIC_PARTNERSHIP"),
	// Enhancement 35522 rkalkir
	NEW_MEM_MARRIAGE_OR_DOMESTIC_PARTNERSHIP("NEW_MEM_MARRIAGE_OR_DOMESTIC_PARTNERSHIP"),
	NEW_APP_NO_LONGER_INCARCERATED("NEW_APP_NO_LONGER_INCARCERATED"),
	NEW_APP_IMMIG_STAT_CHANGED_CITIZEN("NEW_APP_IMMIG_STAT_CHANGED_CITIZEN"),
	NEW_APP_GAINED_A_DEPENDENT("NEW_APP_GAINED_A_DEPENDENT"),
	NEW_APP_LOST_LOOSING_MEC("NEW_APP_LOST_LOOSING_MEC"),
	NEW_APP_PERMENANT_MOVE_TO_NYS("NEW_APP_PERMENANT_MOVE_TO_NYS"),
	NEW_APP_PREGNANCY("NEW_APP_PREGNANCY"),
	NEW_MEM_PREGNANCY("NEW_MEM_PREGNANCY"),
	PREGNANCY("PREGNANCY"),
	
	NEW_MEM_MEMBER_AIAN_STATUS_CHANGE("NEW_MEM_MEMBER_AIAN_STATUS_CHANGE"),
	NEW_MEM_NO_LONGER_INCARCERATED("NEW_MEM_NO_LONGER_INCARCERATED"),
	NEW_MEM_IMMIG_STAT_CHANGED_CITIZEN("NEW_MEM_IMMIG_STAT_CHANGED_CITIZEN"),
	NEW_MEM_LOST_LOOSING_MEC("NEW_MEM_LOST_LOOSING_MEC"),
	NEW_MEM_MOVE_TO_NYS("NEW_MEM_MOVE_TO_NYS"),
	NEW_MEM_GAINED_A_DEPENDENT("NEW_MEM_GAINED_A_DEPENDENT"),
	
	MEMBER_AIAN_STATUS_CHANGE("MEMBER_AIAN_STATUS_CHANGE"),
	NO_LONGER_INCARCERATED("NO_LONGER_INCARCERATED"),
	IMMIG_STAT_CHANGED_CITIZEN("IMMIG_STAT_CHANGED_CITIZEN"),
	LOST_LOOSING_MEC("LOST_LOOSING_MEC"),
	/* CR 1132 */
	MEMBER_CHANGE_LOST_LOOSING_MEC("MEMBER_CHANGE_LOST_LOOSING_MEC"),
	/* CR 1132 */
	MOVE_TO_NYS("MOVE_TO_NYS"),
	MOVE_WITHIN_NYS("MOVE_WITHIN_NYS"),
	GAINED_A_DEPENDENT("GAINED_A_DEPENDENT"),
	DECEASED("DECEASED"),
	MEMBER_PROGRAM_CHANGED("MEMBER_PROGRAM_CHANGED"),
	MEMBERS_CHANGED("MEMBERS_CHANGED"),
	MEMBERS_CHANGED_DECEASED("MEMBERS_CHANGED_DECEASED"),
	MEMBERS_CHANGED_DIVORCED("MEMBERS_CHANGED_DIVORCED"),
	MEMBERS_CHANGED_LEGALLY_SEPERATED("MEMBERS_CHANGED_LEGALLY_SEPERATED"),
	MEMBERS_CHANGED_NO_LONGER_DOMESTIC_PARTNER("MEMBERS_CHANGED_NO_LONGER_DOMESTIC_PARTNER"),
	MEMBERS_CHANGED_MOVED_OUT_OF_STATE("MEMBERS_CHANGED_MOVED_OUT_OF_STATE"),
	MEMBERS_CHANGED_COVERED_BY_ANOTHER_PLAN("MEMBERS_CHANGED_COVERED_BY_ANOTHER_PLAN"),
	MEMBERS_CHANGED_IN_ELIGIBLE_DUE_TO_AGE("MEMBERS_CHANGED_IN_ELIGIBLE_DUE_TO_AGE"),
	MEMBERS_CHANGED_NO_LONGER_IN_HH("MEMBERS_CHANGED_NO_LONGER_IN_HH"),
	MEMBER_NEWELY_ELIGIBLE("MEMBER_NEWELY_ELIGIBLE"),
	SEP_CSR_OVERRIDE("SEP_CSR_OVERRIDE"),
	HH_MEMBER_RETRO_ELIGIBLE("HH_MEMBER_RETRO_ELIGIBLE"),
	HH_MEMBER_TPLREE_CHANGED("HH_MEMBER_TPLREE_CHANGED"),
	HH_MEMBER_ELG_DATE_CHANGED("HH_MEMBER_ELG_DATE_CHANGED"),
	//Added as part of defect 32609
	HH_MEMBER_ELG_END_DATE_CHANGED_FFS("HH_MEMBER_ELG_END_DATE_CHANGED_FFS"),
	HH_MEMBER_ELG_END_DATE_CHANGED_MMC("HH_MEMBER_ELG_END_DATE_CHANGED_MMC"),
	HH_MEMBER_ELG_END_DATE_CHANGED_CHIP("HH_MEMBER_ELG_END_DATE_CHANGED_CHIP"),
	//defect 32609 End
	HH_MEMBER_RENEWAL_UPDATE("HH_MEMBER_RENEWAL_UPDATE"),
	
	/**
	 * CR 111 : Death Match
	 */
	
	//HH_MEMBER_DECEASED("HH_MEMBER_DECEASED"),
	
	//Added as part of Enhancement 34284
	NEW_APP_NO_INSURANCE_TAX_PENALTY("NEW_APP_NO_INSURANCE_TAX_PENALTY"),
	NEW_MEM_NO_INSURANCE_TAX_PENALTY("NEW_MEM_NO_INSURANCE_TAX_PENALTY"),
	MEMBER_NO_INSURANCE_TAX_PENALTY("MEMBER_NO_INSURANCE_TAX_PENALTY"),
	
	//Added for Defect Fix 44193
	REINSTATE_ISSUER("REINSTATE_ISSUER"),	
	
	/**
	 * System events (age-out's etc..)
	 */
	CHIP_CHILD_TURNS_19("CHIP_CHILD_TURNS_19"),
	CATASTROPHIC_AGE_OUT_30("CATASTROPHIC_AGE_OUT_30"),
	CHILD_ON_CHILD_POLICY_TURNS_21_QHP("CHILD_ON_CHILD_POLICY_TURNS_21_QHP"),
	CHILD_ON_CHILD_POLICY_TURNS_21_APTC("CHILD_ON_CHILD_POLICY_TURNS_21_APTC"),
	CHILD_PARENTS_PLAN_AGE_OUT_26("CHILD_PARENTS_PLAN_AGE_OUT_26"),
	CHILD_PARENTS_PLAN_AGE_OUT_30("CHILD_PARENTS_PLAN_AGE_OUT_30"),
	DEP_FAM_DENTAL("DEP_FAM_DENTAL"),
	CHILD_ONLY_DENTAL("CHILD_ONLY_DENTAL"),
	POST_PARTUM("POST_PARTUM"),
	HH_MEMBER_CASE_REF_DIST("HH_MEMBER_CASE_REF_DIST"),
	EMAIL_ADDRESS_INVALIDATED("EMAIL_ADDRESS_INVALIDATED"),
	EMAIL_ADDRESS_VALIDATED("EMAIL_ADDRESS_VALIDATED"),
	MAILING_ADDRESS_INVALIDATED("MAILING_ADDRESS_INVALIDATED"),
	MAILING_ADDRESS_VALIDATED("MAILING_ADDRESS_VALIDATED"),
	PERSON_LIV_IND_IGNORED("PERSON_LIV_IND_IGNORED"),
	PERSON_LIV_IND_ALIVE("PERSON_LIV_IND_ALIVE"),
	PERSON_LIV_IND_NOT_ALIVE("PERSON_LIV_IND_NOT_ALIVE"),
	CHANGE_ACCT_STATUS_ACTIVE("CHANGE_ACCT_STATUS_ACTIVE"),
	CHANGE_ACCT_STATUS_INACTIVE("CHANGE_ACCT_STATUS_INACTIVE"),
	BO_RETRO_FFS_OVERRIDE("BO_RETRO_FFS_OVERRIDE"),
	BO_RETRO_MEDICAID_OVERRIDE("BO_RETRO_MEDICAID_OVERRIDE"),/* CR 1227 Under Cons Vipul*/
	BO_RETRO_NOTICE_GENERATION("BO_RETRO_NOTICE_GENERATION"),/* CR 1227 Under Cons Vipul*/
	ADD_NEW_MEMBER_IN_TERM_PLAN("ADD_NEW_MEMBER_IN_TERM_PLAN"),
	COVERAGE_END_DATE_CHANGED_TERM_PLAN("COVERAGE_END_DATE_CHANGED_TERM_PLAN"),
	ELIGIBILITY_OVERRIDDEN("ELIGIBILITY_OVERRIDDEN"),
	/* START CR577*/
	TPL_RRE_OVERRIDE("TPL_RRE_OVERRIDE"),
	TPL_RRE_OVERRIDDEN("TPL_RRE_OVERRIDDEN"),
	TPL_RRE_PUSHED("TPL_RRE_PUSHED"),
	TPL_RRE_PUSH_IGNORED("TPL_RRE_PUSH_IGNORED"),
	TPL_RRE_PULLED("TPL_RRE_PULLED"),
	TPL_RRE_PUSH("TPL_RRE_PUSH"),
	PUBLIC_MEC("PUBLIC_MEC"),
	PUBLIC_MEC_FAILED("PUBLIC_MEC_FAILED"),
	TPL_RRE_PULL_FAILED("TPL_RRE_PULL_FAILED"),
	TPL_RRE_PUSH_FAILED("TPL_RRE_PUSH_FAILED"),
	/* END CR577*/
	USER_AGREED_TO_DEATH_INFO("USER_AGREED_TO_DEATH_INFO"),
	USER_DISAGREED_TO_DEATH_INFO("USER_DISAGREED_TO_DEATH_INFO"),
	/*Added for CR 588 * by sbhanda - start */
	FILED_TAXES_AND_INCURRED_PENALTY("FILED_TAXES_AND_INCURRED_PENALTY"),
	PRG_CHNG_THAT_ALLOW_SEP("PRG_CHNG_THAT_ALLOW_SEP"),
	DEATH_OF_HH_MEMBER("DEATH_OF_HH_MEMBER"),
	DIVORCED_END_OF_PARTNERSHIP("DIVORCED_END_OF_PARTNERSHIP"),
	MEMBER_MOVED_OUT_OF_HOUSE_HOLD("MEMBER_MOVED_OUT_OF_HOUSE_HOLD"),
	NO_LONGER_ELG_DUE_TO_AGE("NO_LONGER_ELG_DUE_TO_AGE"),
	MOVE_TO_OR_WITHIN_NYS("MOVE_TO_OR_WITHIN_NYS"),
	COVERED_BY_ANOTHER_PLAN("COVERED_BY_ANOTHER_PLAN"),
	OTHER("OTHER"),
	APP_MARRIAGE_OR_DOMESTIC_PARTNERSHIP("APP_MARRIAGE_OR_DOMESTIC_PARTNERSHIP"),
	INDIVIDUAL_TURNS_21_EPP("INDIVIDUAL_TURNS_21_EPP"),
	INDIVIDUAL_TURNS_65_EPP("INDIVIDUAL_TURNS_65_EPP"),
	VOTER_REGISTRATION_MAILED("VOTER_REGISTRATION_MAILED"),
	FIVE_YEAR_BAR_EPP("FIVE_YEAR_BAR_EPP"),
	
	//CR1327
	CHP_NB_COVERAGE_START_DT_SELECTION("CHP_NB_COVERAGE_START_DT_SELECTION"),
	CHP_NB_COVERAGE_START_DT_SELECTION_BO_USER("CHP_NB_COVERAGE_START_DT_SELECTION_BO_USER"),
	CHP_NB_COVERAGE_START_DT_SELECTION_AUTO_ENROLL("CHP_NB_COVERAGE_START_DT_SELECTION_AUTO_ENROLL"),
	
	//CR1140
	ELG_RESULT_EPP_AID_CATEGORY_CHANGE("ELG_RESULT_EPP_AID_CATEGORY_CHANGE"),
	HH_MEMBER_ELG_END_DATE_CHANGED_EPP("HH_MEMBER_ELG_END_DATE_CHANGED_EPP"),
	MEMBER_ELIGIBLE_CHILD_CARE_WORKER("MEMBER_ELIGIBLE_CHILD_CARE_WORKER"),
	NEW_APP_ELIGIBLE_CHILD_CARE_WORKER("NEW_APP_ELIGIBLE_CHILD_CARE_WORKER"),
	NEW_MEM_ELIGIBLE_CHILD_CARE_WORKER("NEW_MEM_ELIGIBLE_CHILD_CARE_WORKER"),
	/*Added for CR 588 * by sbhanda - end */
	
	//CR1151
	MA_DEEMED_NB_AND_CITIZEN_IDENTIFIED("MA_DEEMED_NB_AND_CITIZEN_IDENTIFIED"),
	MA_DEEMED_NB_IDENTIFIED("MA_DEEMED_NB_IDENTIFIED"),
	MA_DEEMED_NB_13MON_AGEOUT("MA_DEEMED_NB_13MON_AGEOUT"),
	
	SHELL_ACCNT_CREATED("SHELL_ACCNT_CREATED"),
	TEMP_ACCNT_CREATED("TEMP_ACCNT_CREATED"),
	SHELL_TO_TEMP_ACCNT_CONVERSION("SHELL_TO_TEMP_ACCNT_CONVERSION"),
	SHELL_ACCNT_EXPIRED("SHELL_ACCNT_EXPIRED"),
	
	//Enhancement 44177
	OVERRIDE_HIX_ID("OVERRIDE_HIX_ID"),
	HIX_ID_LINKED("HIX_ID_LINKED"),
	
	//CR1142
    INDIVIDUAL_TURNS_65_MEDICAID("INDIVIDUAL_TURNS_65_MEDICAID"),
    
    ISSUER_TRIGGERED_SNP_DISENROLLMENT("ISSUER_TRIGGERED_SNP_DISENROLLMENT"),
	AUTO_ASSIGNMENT_MMC("AUTO_ASSIGNMENT_MMC"),
	
	//CR254
	CHIP_PREMIUM_LOCK_ENDING("CHIP_PREMIUM_LOCK_ENDING"),
	CHIP_PREMIUM_EFFECTUATION_RUN("CHIP_PREMIUM_EFFECTUATION_RUN"),
	
	//Enhancement 52568
	COVERAGE_DATE_OVERRIDE("COVERAGE_DATE_OVERRIDE"),
	COVERAGE_DATE_OVERRIDE_QHP("COVERAGE_DATE_OVERRIDE_QHP"),
	
	
	//CR1186
	EMEDNY_FORCED_CLOSURE("FORCED_CLOSURE"),	
	
	//CR1172
	DAI_CODE_V1("DAI_CODE_V1"),
	DAI_CODE_V2("DAI_CODE_V2"),
	DAI_CODE_V3("DAI_CODE_V3"),
	DAI_CODE_V4("DAI_CODE_V4"),	
	DAI_CODE_V0("DAI_CODE_V0"),
	
	//CR554
	
	ISSUER_NONPAYMENT_TERMINATION("ISSUER_NONPAYMENT_TERMINATION"),

	// CR522 - added the clock name into the events
	AMERICAN_INDIAN_90("AMERICAN INDIAN 90 clock opened"),
	APTC_INCOME_90("APTC INCOME 90 clock opened"),
	
	CHIP_CURRENT_INCOME_60("CHIP CURRENT INCOME 60 clock opened"),
	CHIP_INCOME_60("CHIP INCOME 60 clock opened"),
	CITIZENSHIP_90("CITIZENSHIP 90 clock opened"),
	CITIZENSHIP_DISCREPANCY_90("CITIZENSHIP DISCREPANCY 90 clock opened"),
	EPP_INCOME_90("EPP INCOME 90 clock opened"),
	IMMIGRATION_90("IMMIGRATION 90 clock opened"),
	IMMIGRATION_VETERAN_90("IMMIGRATION VETERAN 90 clock opened"),
	
	INCARCERATION_10("INCARCERATION 10 clock opened"),
	INCARCERATION_30("INCARCERATION 30 clock opened"),
	INCARCERATION_90("INCARCERATION 90 clock opened"),
	
	MEC_MCR_45("MEC MCR 45 clock opened"),
	MEC_MEDAB_45("MEC MEDAB 45 clock opened"),
	MEC_PEACE_45("MEC PEACE 45 clock opened"),
	MEC_TRI_45("MEC TRI 45 clock opened"),
	MEC_TRI_90("MEC TRI 90 clock opened"),
	MEC_TRI_TERMIN_1("MEC TRI TERMIN 1 clock opened"),
	MEC_VET_45("MEC VET 45 clock opened"),
	
	MEDICAID_CURRENT_INCOME_15("MEDICAID CURRENT INCOME 15 clock opened"),
	MEDICAID_INCOME_15("MEDICAID INCOME 15 clock opened"),
	MEDICAID_INCOME_TPL_15("MEDICAID INCOME TPL 15 clock opened"),
	
	RESI_SPL_RULE_CHILD_SCHL_ENRL_90("RESI SPL RULE CHILD SCHL ENRL 90 clock opened"),
	RESI_SPL_RULE_HOME_OWNERSHIP_90("RESI SPL RULE HOME OWNERSHIP 90 clock opened"),
	RESI_SPL_RULE_HOME_RENTAL_90("RESI SPL RULE HOME RENTAL 90 clock opened"),
	RESI_SPL_RULE_LGL_PERMRESI_90("RESI SPL RULE LGL PERMRESI 90 clock opened"),
	RESI_SPL_RULE_WORK_DOCS_90("RESI SPL RULE WORK DOCS 90 clock opened"),
	RETRO_INCOME_15("RETRO INCOME 15 clock opened"),
	RETRO_MON1_INCOME_15("RETRO MON1 INCOME 15 clock opened"),
	RETRO_MON2_INCOME_15("RETRO MON2 INCOME 15 clock opened"),
	RETRO_MON3_INCOME_15("RETRO MON3 INCOME 15 clock opened"),
	SR_ABSENT_PARENT_90("SR ABSENT PARENT 90 clock opened"),
	SSN_90("SSN 90 clock opened"),
	STATE_RESIDENCY_90("STATE RESIDENCY 90 clock opened"),
	//CR 1193
	WILLING_TO_COOPERATE("Willingness to cooperate question answered"),
	ADDRESS_DETAILS_VERIFIED("ADDRESS_DETAILS_VERIFIED"),
	MOVE_ADDRESS_IDENTIFIED("MOVE_ADDRESS_IDENTIFIED"),
	SUGGESTED_ADDRESS_IDENTIFIED("SUGGESTED_ADDRESS_IDENTIFIED"),
	//Defect 61133
	OTDA_NEWBORN_ADDITION("Newborn added via OTDA Hospital Interface"),
	CBIC_REPLACEMENT_REQUEST("CBIC_REPLACEMENT_REQUEST"),
	//CR1455
	IMMG_GRANTDATE_90("Immigration GrantDate 90 day clock opened"),
	POST_PARTUM_PREV_CLK_EXPIRY("POST_PARTUM_PREV_CLK_EXPIRY"),
	// CR 1398
	ELG_RESULT_MEDICAID_DOCCS_TYPE_CHANGE("ELG_RESULT_MEDICAID_DOCCS_TYPE_CHANGE"),
	//CR1606
	STALE_ELIGIBILITY("STALE_ELIGIBILITY"),
	
	DOCCS_UNDER_CUSTODY_PROCESSED("DOCCS_UNDER_CUSTODY_PROCESSED"),
	DOCCS_PRE_RELEASE_PROCESSED("DOCCS_PRE_RELEASE_PROCESSED"),
	DOCCS_PRE_RELEASE_CANCEL_PROCESSED("DOCCS_PRE_RELEASE_CANCEL_PROCESSED"),
	DOCCS_RELEASE_IDENTIFIED_01("DOCCS_RELEASE_IDENTIFIED_01"),
	DOCCS_RELEASE_IDENTIFIED_02("DOCCS_RELEASE_IDENTIFIED_02"),
	DOCCS_RELEASE_IDENTIFIED_03("DOCCS_RELEASE_IDENTIFIED_03"),
	DOCCS_RELEASE_IDENTIFIED_04("DOCCS_RELEASE_IDENTIFIED_04"),
	DOCCS_RELEASE_IDENTIFIED_05("DOCCS_RELEASE_IDENTIFIED_05"),
	DOCCS_RELEASE_IDENTIFIED_06("DOCCS_RELEASE_IDENTIFIED_06"),
	DOCCS_RELEASE_IDENTIFIED_07("DOCCS_RELEASE_IDENTIFIED_07"),
	DOCCS_RELEASE_IDENTIFIED_08("DOCCS_RELEASE_IDENTIFIED_08"),
	DOCCS_RELEASE_IDENTIFIED_09("DOCCS_RELEASE_IDENTIFIED_09");
	
	
	private String val;
	
	private EvtEventName(String value){
		val = value;
	}
	
	public static EvtEventName getEnum(String value){
		for(EvtEventName evtRefType : EvtEventName.values()){
			if(evtRefType.name().equalsIgnoreCase(value)){
				return evtRefType;
			}
		}
		return null;
	}
	
	public static EvtEventName getEnumbyValue(String value){
		for(EvtEventName evtRefType : EvtEventName.values()){
			if(evtRefType.getVal().equalsIgnoreCase(value)){
				return evtRefType;
			}
		}
		return null;
	}

	public String getVal() {
		return val;
	}

	public void setVal(String val) {
		this.val = val;
	}
	
	/**
	 * 
	 * @param eventName
	 * @return can be used only for disenrollment events.
	 * CR#555 - An event  REASON_CODE would be displayed on Events tab page 
	 */
	public static String getDisenrollEventDescription(String eventName){
		
		if(eventName.equals(EvtEventName.ENROLLMENT_DELETE.name())){
			return HXConstants.ENROLLMENT_DELETE_EVENT_DESC;
		}else if(eventName.equals(EvtEventName.ISSUER_NONPAYMENT_TERMINATION.name())){
			return HXConstants.ISSUER_NONPAYMENT_EVENT_DESC;
		}else if(eventName.equals(EvtEventName.ISSUER_TRIGGERED_SNP_DISENROLLMENT.name())){
			return HXConstants.ISSUER_TRIGGERED_SNP_DISENROLLMENT_DESC;
		}
		return null;
	} 

}