package com.hcentive.eligibility.poc.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Eligibility Main processing flow state pojo.")
public class EligibilityMain implements java.io.Serializable {
	private boolean preCheckStale;
	private boolean inEligible;
	private boolean fplComparedToMedicaidLevel;
	private boolean nonCapabitibleIndicator;
	private boolean clockScheduled;
	private boolean pregnant;

	public boolean isPreCheckStale() {
		return preCheckStale;
	}

	public void setPreCheckStale(boolean preCheckStale) {
		this.preCheckStale = preCheckStale;
	}

	public boolean isInEligible() {
		return inEligible;
	}

	public void setInEligible(boolean inEligible) {
		this.inEligible = inEligible;
	}

	public boolean isFplComparedToMedicaidLevel() {
		return fplComparedToMedicaidLevel;
	}

	public void setFplComparedToMedicaidLevel(boolean fplComparedToMedicaidLevel) {
		this.fplComparedToMedicaidLevel = fplComparedToMedicaidLevel;
	}

	public boolean isNonCapabitibleIndicator() {
		return nonCapabitibleIndicator;
	}

	public void setNonCapabitibleIndicator(boolean nonCapabitibleIndicator) {
		this.nonCapabitibleIndicator = nonCapabitibleIndicator;
	}

	public boolean isClockScheduled() {
		return clockScheduled;
	}

	public void setClockScheduled(boolean clockScheduled) {
		this.clockScheduled = clockScheduled;
	}

	public boolean isPregnant() {
		return pregnant;
	}

	public void setPregnant(boolean pregnant) {
		this.pregnant = pregnant;
	}

	public EligibilityMain() {
	}

	public EligibilityMain(boolean preCheckStale, boolean inEligible,
			boolean fplComparedToMedicaidLevel,
			boolean nonCapabitibleIndicator, boolean clockScheduled,
			boolean pregnant) {
		this.preCheckStale = preCheckStale;
		this.inEligible = inEligible;
		this.fplComparedToMedicaidLevel = fplComparedToMedicaidLevel;
		this.nonCapabitibleIndicator = nonCapabitibleIndicator;
		this.clockScheduled = clockScheduled;
		this.pregnant = pregnant;
	}
}
