package com.hcentive.utils.ext;

public enum HXMECCustomProgramTypeEnum {
	MEDI, TRIC, VHPC, PECO, CHIP, MEDICAID, BHPC, MEDICARE, TRICARE, PEACE_CORPS, AMERI_CORPS, MEC_TRI_TERMIN, MEC_PEACE_TERMIN, MEC_AMERI_TERMIN,VHP
}
