package com.hcentive.utils.ext;

public enum HXProgramConversionStatusEnum {
	NEW, RESEQUENCE, ELG_DETERMINED, RESEQ_FAILED, AEQ_FAILED, AEQ_AUTO_ASSIGNED, AEQ_AUTO_NOT_ASSIGNED, RESEQ_CANCELLED, AEQ_CANCELLED,ACTIVE_RENEWAL;
}
