package com.hcentive.utils.ext;

public enum ReseqReasonCodeEnum {
	CHIP_CHILD_TURNS_19,
	CATASTROPHIC_AGE_OUT_30,
	CHILD_ON_CHILD_POLICY_TURNS_21_QHP,
	CHILD_ON_CHILD_POLICY_TURNS_21_APTC,
	CHILD_PARENTS_PLAN_AGE_OUT_26,
	CHILD_PARENTS_PLAN_AGE_OUT_30,
	DEP_FAM_DENTAL,
	POST_PARTUM,
	POST_PARTUM_PREV_CLK_EXPIRY,
	PROPOSED,
	NO_INCOME,
	DEATH_MATCH,
	INDIVIDUAL_TURNS_21_EPP,
	INDIVIDUAL_TURNS_65_EPP,
	FIVE_YEAR_BAR_EPP,
	CONV_JOB_EPP,
	MA_DEEMED_NB_13MON_AGEOUT,
	CHIP_PREMIUM_LOCK_ENDING,
	RENEWAL_SYSGEN,
	UNDELIVERED_MAIL_DATA
}