
package org.hx.commonservices.cinclearance.hbe;

import javax.xml.ws.WebFault;
import org.hx.commonservices.cinclearance.exception.ServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "serviceException", targetNamespace = "http://org/hx/commonservices/CINClearance/Exception/")
public class CinServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CinServiceException(String message, ServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public CinServiceException(String message, ServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.hx.commonservices.cinclearance.exception.ServiceException
     */
    public ServiceException getFaultInfo() {
        return faultInfo;
    }

}
