package com.hcentive.shop.activity.domain;

public enum ActivityGroupNameEnum {
	CLASS,
	COMPANY_SETTINGS,
	ELIGIBILITY,
	EMPLOYEE_ACCOUNT,
	EMPLOYER_ACCOUNT,
	ENROLLMENT,
	GROUPSETUP,
	ACCOUNT_DETAILS,
	COMMENTS,
	BROKER_RECERT,
	BROKER_ACCOUNT,
	NAVIGATOR_ACCOUNT,
	CAC_ACCOUNT,
	AGENT_ACCOUNT
	
}
