package com.hcentive.rulesengine.domain;

public enum RuleKey {
	MEDICAID_AGE_MAX, MEDICAID_AGE_INFANT, MEDICAID_YOUTH_MIN, MEDICAID_YOUTH_MAX, MEDICAID_AGE_KID, MEDICAID_FPL_MAX, 
	MEDICAID_FPL_MID, MEDICAID_FPL_MIN, MEDICAID_CHILD_FPL_MIN, MEDICAID_FPL_YOUTH, 
	MEDICAID_RE_SEQ_END_DATE, TITLE_II_PLAN_YEAR, EXCL_VERIFICATION_CLOCK,
	//CR1527:PPSD Special Rules Exclusion Clocks.
	PPSD_EXCL_CLOCK,
	MEDICAID_PRUCOL_FPL_MAX, CHIP_AGE_MAX, CHIP_FPL_MAX,	CHIP_FPL_MIN, CHIP_DSFPL_MAX,	CHIP_DSFPL_MIN,  
	APTC_FPL_MAX, APTC_FPL_MIN, APTC_DSFPL_MIN, APTC_DSFPL_MAX, APTC_IRSDSFPL_MIN, APTC_IRSDSFPL_MAX,
	APTC_PREMIUM_FPL_MIN, APTC_PREMIUM_FPL_MAX, APTC_ESI_INCOME_PERCENT,
	CSR_FPL_MAX, CSR_FPL_MIN, RULE_VERSION, FAMILYPLANNING_FPL_MIN, FAMILYPLANNING_FPL_MAX, FPL_100_HH_1, FPL_100_HH_2, FPL_100_HH_3,
	FPL_100_HH_4, FPL_100_HH_5, FPL_100_HH_6, FPL_100_HH_7, FPL_100_HH_8, FPL_100_HH_ADDNL,
	
	NC_INCOME_AGE, 
	
	NC_INCOME_SD_EI_AGE, 
	NC_INCOME_SD_EI_AGE_OR_BLIND,
	NC_INCOME_SD_EI_AGE_AND_BLIND, 
	
	NC_INCOME_MD_EI_AGE, 
	NC_INCOME_MD_EI_AGE_OR_BLIND, 
	NC_INCOME_MD_EI_AGE_AND_BLIND, 
	
	NC_INCOME_SD_UI_AGE,
	NC_INCOME_SD_UI_AGE_OR_BLIND, 
	NC_INCOME_SD_UI_AGE_AND_BLIND, 
	
	NC_INCOME_MD_UI_AGE, 
	NC_INCOME_MD_UI_AGE_OR_BLIND, 
	NC_INCOME_MD_UI_AGE_AND_BLIND,
	
	NC_INCOME_SD_GI_AGE,
	NC_INCOME_SD_GI_AGE_UPPER_LIMIT,
	NC_INCOME_SD_GI_AGE_UPPER_PLUS,
	NC_INCOME_SD_GI_AGE_OR_BLIND,
	NC_INCOME_SD_GI_AGE_OR_BLIND_UPPER_LIMIT,
	NC_INCOME_SD_GI_AGE_OR_BLIND_UPPER_PLUS,
	NC_INCOME_SD_GI_AGE_AND_BLIND,
	NC_INCOME_SD_GI_AGE_AND_BLIND_UPPER_LIMIT,
	NC_INCOME_SD_GI_AGE_AND_BLIND_UPPER_PLUS,
	
	NC_INCOME_MD_GI_AGE,
	NC_INCOME_MD_GI_AGE_UPPER_LIMIT,
	NC_INCOME_MD_GI_AGE_UPPER_PLUS,
	NC_INCOME_MD_GI_AGE_OR_BLIND,
	NC_INCOME_MD_GI_AGE_OR_BLIND_UPPER_LIMIT,
	NC_INCOME_MD_GI_AGE_OR_BLIND_UPPER_PLUS,
	NC_INCOME_MD_GI_AGE_AND_BLIND,
	NC_INCOME_MD_GI_AGE_AND_BLIND_UPPER_LIMIT,
	NC_INCOME_MD_GI_AGE_AND_BLIND_UPPER_PLUS,
	
	LIF_LVL_100_HH_1,
	LIF_LVL_100_HH_2,
	LIF_LVL_100_HH_3,
	LIF_LVL_100_HH_4,
	LIF_LVL_100_HH_5,
	LIF_LVL_100_HH_6,
	LIF_LVL_100_HH_7,
	LIF_LVL_100_HH_8,
	LIF_LVL_100_HH_9,
	LIF_LVL_100_HH_10,
	LIF_LVL_100_HH_ADDNL,
	MEDICAID_CHILD_FPL_MAX,
	MEDICAID_ADULT_LIVING_WITH_PARENT_FPL,
	
	FOSTERCARE_AGE_MIN,
	FOSTERCARE_AGE_MAX,
	
	IGNORE_APTC_ERROR,
	OOP_FPL, OOP_FPL_LVL_1, OOP_FPL_LVL_2, OOP_FPL_LVL_3, OOP_AMT_LVL_1, OOP_AMT_LVL_2, OOP_AMT_LVL_3,
	ADD_VERF_DUE_DATE_BUFFER,
	DISABLE_ENROLLMENT,
	//Hitting services
	HIT_SSA_COMPOSITE,
	MASTER_RESEQUENCE_IND, MASTER_RESEQUENCE_RUN_DATE,
	VLP_OFFLINE,
	MEC_OFFLINE, VALID_MEC_INS_END_DATE,
	VALID_ESI_MEC_INS_END_DATE, RULE_DRL_FILE_LOCATION,
	RULE_META_DATA_LOG_EXEC_ORDER,
	DETERMINE_ELG_AS_OF,
	ELG_DTM_THRESHOLD_DATE,
	CHIP_ESI_AGE,
	CHIP_ESI_FPL_MIN,
	CHIP_ESI_FPL_MAX,
	PO_ELG_MED_SKIP_DAYS,
	SEP_IN_DAYS, SEP_EXT_IN_DAYS,
	SPE_PLN_SEL_TIME, SEP_EXT_PLN_SEL_TIME,
	PMEC_SEP_E_DAYS,
	ADD_RETRO_VERF_DUE_DATE_BUFFER,
	ADD_15_DAY_CLOCK_VERF_DUE_DATE_BUFFER,
	MEDICAID_AGE_LIMIT, 
	MEC_AGE_MAX,
	RENEWAL_YEAR,
	APTC_FPL_LT_133_MIN,
	APTC_FPL_LT_133_MAX,
	APTC_FPL_133_150_MIN,
	APTC_FPL_133_150_MAX,
	APTC_FPL_150_200_MIN,
	APTC_FPL_150_200_MAX,
	APTC_FPL_200_250_MIN,
	APTC_FPL_200_250_MAX,
	APTC_FPL_250_300_MIN,
	APTC_FPL_250_300_MAX,
	APTC_FPL_300_400_MIN,
	APTC_FPL_300_400_MAX,
	RENEWAL_RESEQ_NEW_APPS, 
	
	//CR111
	IND_CLK_REQUIRED,
	PVC_CLK_REQUIRED,
	SSA_CLK_REQUIRED,
	RRV_CLK_REQUIRED,
	USR_CLK_REQUIRED,
	CSR_CLK_REQUIRED, CLK_PRECEDENCE, MEDICAID_DECEASED_CLK, MEDICAID_DECEASED_CLK_PERIOD, CHIP_DECEASED_CLK_PERIOD, QHP_DECEASED_CLK_PERIOD,
	MEDICAID_DECEASED_CLK_BUFFER, CHIP_DECEASED_CLK_BUFFER, QHP_DECEASED_CLK_BUFFER, APTC_DECEASED_CLK_PERIOD, APTC_DECEASED_CLK_BUFFER,EPP_DECEASED_CLK_PERIOD,
	EPP_DECEASED_CLK_BUFFER,
	
	//CR1140 - Introducing BHP program and Retiring APTCPP program
	APTC_PP_TO_EPP_SWITCH_DATE,
	EPP_FPL_LVL_1,
	EPP_FPL_LVL_2,
	EPP_FPL_LVL_3,
	EPP_FPL_LVL_4,
	EPP_AGE_MAX,
	EPP_AGE_MIN,
	
	//CR1182 - Coverage Preference
	ACTIVE_COVERAGE_CHECK_DATE_FOR_NEW_CONSUMER,
	
	// CR522 change-vmannep INFINITE Date
	INFINITE_DATE,
	// added for CR#522
	VER_DOC_MIN_VALID_PER_ID,
	//CR1132
	TENDAY_NOTICE_RULE_DAYS,
	//Cr1269
	NO_SHOW_AT_MEMBER_LVL,

	//jkadimi - CR1329 - changes - Start
	SLCSP_EFFECTIVE_START_DATE,
	ALLOW_DISABLED_KID_IN_GROUP_EFFECTIVE_START_DATE,
	//jkadimi - CR1329 - changes - End
	//CR1327
	CHIP_NEWBORN_VALID_PER_DAYS,
	//CR 1361
	NYSHIP_RECORD_VALID_UNTIL_STRATEGY,
	
	//jkadimi - CR1420 - changes - Start
	ORGAN_DONOR_REGISTRATION_ENABLED,
	ORGAN_DONOR_REGISTRATION_MINIMUM_AGE_IN_YEARS,
    //jkadimi - CR1420 - changes - End
	
	//CR1398 - changes - Start
	UNDER_CUSTODY_WEIGHTAGE,
	RELEASE_WEIGHTAGE,
	PRERELEASE_WEIGHTAGE,
	UPDATE_WEIGHTAGE,
	CANCEL_WEIGHTAGE,
	//CR1398 - changes - Start
	
	
	//CR1454 Changes
	HXSUR_HXSUR, HXSUR_HXLTC, HXSUR_HXDAB, HXSUR_HXFOS, HXSUR_HXRET, HXLTC_HXSUR, HXLTC_HXLTC, HXLTC_HXDAB, HXLTC_HXFOS, HXLTC_HXRET, HXDAB_HXSUR, HXDAB_HXLTC, HXDAB_HXDAB, HXDAB_HXFOS, HXDAB_HXRET, HXFOS_HXSUR,
	HXFOS_HXLTC, HXFOS_HXDAB, HXFOS_HXFOS, HXFOS_HXRET, HXRET_HXSUR, HXRET_HXLTC, HXRET_HXDAB, HXRET_HXFOS, HXRET_HXRET, HXNMD_HXNMD, HXNMD_HXWMD, HXNMD_HXNTX, HXWMD_HXNMD, HXWMD_HXWMD,
	HXWMD_HXNTX, HXNTX_HXNMD, HXNTX_HXWMD, HXNTX_HXNTX, HXNMD_HXSUR,HXNMD_HXLTC, HXNMD_HXDAB, HXNMD_HXFOS, HXNMD_HXRET, HXWMD_HXSUR, HXWMD_HXLTC,
	HXWMD_HXDAB, HXWMD_HXFOS, HXWMD_HXRET, HXNTX_HXSUR, HXNTX_HXLTC, HXNTX_HXDAB, HXNTX_HXFOS, HXNTX_HXRET;
	// CR1454 Changes End
	
}